---
- name: Audit macchine
  hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Check if folder exists
      stat:
        path: "{{ snapshot_path }}"
      register: folder_stat

    - name: Fail if folder does not exist
      fail:
        msg: "The folder {{ snapshot_path }} does not exist."
      when: not folder_stat.stat.exists

    - name: Find snpashot files in the folder base at "{{ snapshot_path }}"
      find:
        paths: "{{ snapshot_path }}"
        patterns: "*.yml"
      register: files

    - name: Fail if not found files
      fail:
        msg: "Not files found."
      when: files.files | length == 0

    - name: Get the last file snapshot
      set_fact:
        last_file: "{{ files.files | sort(attribute='path')  | last  }}"

    - name: Slurp content of file
      slurp:
        src: "{{ last_file.path }}"
      register: file_content

    - name: Load snapshot
      set_fact:
        snaphost: "{{ file_content.content | b64decode | from_yaml }}"

    - name: Get status macchine
      import_tasks: get_status.yml

    - name: Print out Delta status macchine
      set_fact:
        delta:
          services: "{{ snaphost['services'] | difference(services_running) }}"
          ports: "{{ snaphost['ports'] | difference(ports) }}"
          mounts: "{{ snaphost['mounts'] | difference(mounts) }}"
          crontab: "{{ snaphost['crontab'] | difference(crontab) }}"
          envs: "{{ snaphost['envs'] | difference(envs) }}"
          alias: "{{ snaphost['alias'] | difference(alias) }}"

    - name: Check if any delta list is not empty
      assert:
        that:
          - delta.services | length == 0
          - delta.ports | length == 0
          - delta.mounts | length == 0
          - delta.crontab | length == 0
          - delta.envs | length == 0
          - delta.alias | length == 0
        fail_msg: "Non-empty delta lists: services={{ delta.services }}, ports={{ delta.ports }}, mounts={{ delta.mounts }}, crontab={{ delta.crontab }}, envs={{ delta.envs }}, alias={{ delta.alias  }}"
        success_msg: "All delta lists are empty. No differences found."
